name: Deploy TickerQ-UI

on:
  push:
    branches:
      - main  # Trigger the workflow on push to main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      run: |
        docker login registry.arcenox.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t registry.arcenox.com/arcenox/v8_tickerq_ui:latest .
        docker push registry.arcenox.com/arcenox/v8_tickerq_ui:latest

    - name: SSH and run docker-compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /root/v8_tickerq_ui
          docker-compose down
          docker rmi registry.arcenox.com/arcenox/v8_tickerq_ui:latest
          docker-compose up --detach --remove-orphans --force-recreate
